site_name: Appium Device Farm
repo_url: https://github.com/AppiumTestDistribution/appium-device-farm
repo_name: AppiumTestDistribution/appium-device-farm
site_url: https://appium-device-farm-eight.vercel.app/
edit_uri: edit/master/docs
site_description: Documentation for the Appium Device Farm plugin
docs_dir: docs
site_dir: site
theme:
  name: material
  logo: assets/images/appium-logo.png
  favicon: assets/images/appium-logo.png
  custom_dir: docs/overrides
  features:
    - navigation.tabs
  font:
    code: Roboto Mono
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode  
markdown_extensions:
  - meta
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: ''
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons/
extra_css:
  - assets/stylesheets/extra.css
nav:
  - index.md
  - Setup:
    - Hub Setup: hub-setup.md
    - Node Setup: node-setup.md
    - Test Integration: test-integration.md
  - Cloud Execution: cloud.md
  - Configuration:
    - Hub Configuration: hub-configuration.md
    - Node Configuration: node-configuration.md
  - Authentication:
    - User Authentication: user-authentication.md
    - Node Authentication: node-authentication.md
    - Automation Authentication: automation-authentication.md
    - Device Management: device-management.md
    - Best Practices: authentication-best-practices.md
  - troubleshooting.md
  - capabilities.md
  - architecture.md
  - iOS Signing:
    - Device Farm Managed WDA: device-farm-managed-wda.md
    - Manual WDA Setup: manual-wda-setup.md
    - Downloading WDA: downloading-wda.md
    - Creating Provisioning Profile: creating-provisioning-profile.md
    - Resigning WDA: resigning-wda.md
    - tvOS WDA Preparation: tvos-wda-preparation.md
    - Uploading WDA: uploading-wda.md
    - Building from Source: building-wda-from-source.md
  - Reference:
      - server-args.md
      - reference/commands/sample.md
